Support for using mdata-* tools inside a regular zone

diff --git a/cns-hook b/cns-hook
--- a/cns-hook
+++ b/cns-hook
@@ -59,28 +59,70 @@ function update_remotevm {
 		sdc-vmadm update $vmuuid
 }
 
+function mdata_put {
+	local path=/usr/sbin/mdata-put
+	if [ ! -e "$path" ]; then
+		path=/native/usr/sbin/mdata-put
+		if [ ! -e "$path" ]; then
+			echo "ERROR: failed to find mdata-put command" >&2
+			echo "       is this a Triton zone?" >&2
+			exit 1
+		fi
+	fi
+	cmd="$path"
+	if [ -e "/usr/bin/pfexec" ]; then
+		cmd="/usr/bin/pfexec ${cmd}"
+	fi
+	$cmd "$@"
+}
+
+function mdata_delete {
+	local path=/usr/sbin/mdata-delete
+	if [ ! -e "$path" ]; then
+		path=/native/usr/sbin/mdata-delete
+		if [ ! -e "$path" ]; then
+			echo "ERROR: failed to find mdata-delete command" >&2
+			echo "       is this a Triton zone?" >&2
+			exit 1
+		fi
+	fi
+	cmd="$path"
+	if [ -e "/usr/bin/pfexec" ]; then
+		cmd="/usr/bin/pfexec ${cmd}"
+	fi
+	$cmd "$@"
+}
+
 function deploy_challenge {
 	local domain="${1}" tokenfn="${2}" tokenval="${3}"
 
-	local vmuuid
-	case "$(getservice "${domain}")" in
-	cloudapi|adminui|docker)
-		local alias="$(getservice "${domain}")0"
-		vmuuid="$(vmadm lookup alias=$alias)"
-		verifyvm "$domain" "$vmuuid"
-		update_localvm "$vmuuid" "$tokenval"
-		;;
-	manta)
-		local poseidon=$(sdc-useradm get poseidon | json uuid)
-		vmuuid=$(sdc-vmadm list -H -o uuid owner_uuid="$poseidon" alias="loadbalancer" | tail -1)
-		verifyvm "$domain" "$vmuuid"
-		update_remotevm "$vmuuid" "$tokenval"
-		;;
-	*)
-		echo "ERROR: Unknown domain: ${domain}" >&2
-		exit 1
-		;;
-	esac
+	local zname=$(zonename)
+	if [ "$zname" != "global" ]; then
+		verifyvm "$domain" "$zname"
+		mdata_put "triton.cns.acme-challenge" "$tokenval"
+	else
+		local vmuuid
+		case "$(getservice "${domain}")" in
+		cloudapi|adminui|docker)
+			local alias="$(getservice "${domain}")0"
+			vmuuid="$(vmadm lookup alias=$alias)"
+			verifyvm "$domain" "$vmuuid"
+			update_localvm "$vmuuid" "$tokenval"
+			;;
+		manta)
+			local poseidon=$(sdc-useradm get poseidon | json uuid)
+			vmuuid=$(sdc-vmadm list -H -o uuid \
+				owner_uuid="$poseidon" alias="loadbalancer" | \
+				tail -1)
+			verifyvm "$domain" "$vmuuid"
+			update_remotevm "$vmuuid" "$tokenval"
+			;;
+		*)
+			echo "ERROR: Unknown domain: ${domain}" >&2
+			exit 1
+			;;
+		esac
+	fi
 
 	waitfortxt "$domain" "$tokenval"
 
@@ -91,22 +133,33 @@ function deploy_challenge {
 function clean_challenge {
 	local domain="${1}" tokenfn="${2}" tokenval="${3}"
 
-	local vmuuid
-	case "$(getservice "${domain}")" in
-	cloudapi|adminui|docker)
-		local alias="$(getservice "${domain}")0"
-		vmuuid="$(vmadm lookup alias=$alias)"
-		verifyvm "$domain" "$vmuuid"
-		echo "{\"remove_customer_metadata\":[\"triton.cns.acme-challenge\"]}" | \
-			vmadm update "$vmuuid"
-		;;
-	esac
+	local zname=$(zonename)
+	if [ "$zname" != "global" ]; then
+		verifyvm "$domain" "$zname"
+		mdata_delete "triton.cns.acme-challenge"
+	else
+		local vmuuid
+		case "$(getservice "${domain}")" in
+		cloudapi|adminui|docker)
+			local alias="$(getservice "${domain}")0"
+			vmuuid="$(vmadm lookup alias=$alias)"
+			verifyvm "$domain" "$vmuuid"
+			echo "{\"remove_customer_metadata\":[\"triton.cns.acme-challenge\"]}" | \
+				vmadm update "$vmuuid"
+			;;
+		esac
+	fi
 
 	exit 0
 }
 
 function deploy_cert {
 	local domain="${1}" keyfile="${2}" certfile="${3}" fullchainfile="${4}" chainfile="${5}"
+
+	local zname=$(zonename)
+	if [ "$zname" != "global" ]; then
+		exit 0
+	fi
 
 	local vmuuid
 	local certdir="$(dirname "$certfile")"
@@ -165,6 +218,11 @@ function deploy_cert {
 
 function unchanged_cert {
 	local domain="${1}" keyfile="${2}" certfile="${3}" fullchainfile="${4}" chainfile="${5}"
+
+	local zname=$(zonename)
+	if [ "$zname" != "global" ]; then
+		exit 0
+	fi
 
 	local vmuuid
 	local certdir="$(dirname "$certfile")"
